#pragma once

enum BlockId: unsigned char
{
	BLOCKID_AIR,
	BLOCKID_DIRT,
	BLOCKID_GRASS,
	BLOCKID_STONE,
	BLOCKID_COBBLESTONE,
	BLOCKID_COAL,
	BLOCKID_IRON,
	BLOCKID_GOLD,
	BLOCKID_DIAMOND,
	BLOCKID_BEDROCK,
	BLOCKID_WATER,
	BLOCKID_END
};