#pragma once

enum TextureBlockID : unsigned char
{
	TEXTUREID_NOTEXTURE,
	TEXTUREID_DIRT,
	TEXTUREID_GRASS,
	TEXTUREID_GRASS_SIDE,
	TEXTUREID_STONE,
	TEXTUREID_COBBLESTONE,
	TEXTUREID_BEDROCK,
	TEXTUREID_COAL,
	TEXTUREID_IRON,
	TEXTUREID_GOLD,
	TEXTUREID_DIAMOND,
	TEXTUREID_WATER,
	TEXTUREID_END
};